### ISSUE TITLE
感谢你的思维导图！！！！

### ISSUE THREAD

**Issue by github090588** [FennelDumplings/leetcode#1]
这样可以从全貌了解一个知识点，真的太难得了。但是好像算法那部分没覆盖全部吗？

可以加入链表和DP的导图吗？

感谢！

**Comment by FennelDumplings** [comment]
好的呀，DP这块主要是太庞大了，有些点还在写。春节前总可以做好了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FennelDumplings/leetcode-maxed_out"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 晚上11:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FennelDumplings/leetcode-maxed_out] 感谢你的思维导图！！！！ (Issue #1)





 
这样可以从全貌了解一个知识点，真的太难得了。但是好像算法那部分没覆盖全部吗？
 
可以加入链表和DP的导图吗？
 
感谢！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by github090588** [comment]
太感谢了！不急。我正按照你的导图刷题中。真的非常感谢，太有用了。一直在海里游泳，都不知道海有多大。你的导图让我知道了海有多大，这样方便掌控，逐个知识点击破。一万个赞。

另外想问一下你找的这些题都是最经典和最常考的吗？
